---
- name: Mantenimiento total de Ubuntu
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Ejecutar update y full-upgrade
      apt:
        update_cache: yes
        upgrade: full  # Esto equivale a 'sudo apt full-upgrade -y'

    - name: Ejecutar autoremove
      apt:
        autoremove: yes # Esto equivale a 'sudo apt autoremove -y'
