---
- name: Mantenimiento automatico de Ubuntu
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: 1. Actualizar repositorios e instalar actualizaciones seguras
      apt:
        update_cache: yes
        upgrade: safe

    - name: 2. Limpiar basura y dependencias huerfanas (autoremove)
      apt:
        autoremove: yes
